export const songs = [
  {
    id: 101,
    title: 'あいたくて',
    initial: 'あ',
    writer: '工藤直子',
    composer: '新実徳英',
    arranger: '',
  },
  {
    id: 102,
    title: '青の記念日',
    initial: 'あ',
    writer: '長井理佳',
    composer: '横山潤子',
    arranger: '',
  },
  {
    id: 103,
    title: '青葉の歌',
    initial: 'あ',
    writer: '小森香子',
    composer: '熊谷賢一',
    arranger: '',
  },
  {
    id: 104,
    title: 'あかい糸〜先生おめでとう〜',
    initial: 'あ',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 105,
    title: '赤いやねの家',
    initial: 'あ',
    writer: '織田ゆり子',
    composer: '上柴はじめ',
    arranger: '',
  },
  {
    id: 106,
    title: 'あきかん チャ・チャ・チャ！',
    initial: 'あ',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 107,
    title: 'AGAIN',
    initial: 'あ',
    writer: '春畑セロリ',
    composer: '春畑セロリ',
    arranger: '',
  },
  {
    id: 108,
    title: 'あさがお',
    initial: 'あ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 109,
    title: '朝が来た',
    initial: 'あ',
    writer: '村田さち子',
    composer: '上柴はじめ',
    arranger: '',
  },
  {
    id: 110,
    title: '朝靄（あさもや）',
    initial: 'あ',
    writer: '藤岡正明',
    composer: '藤岡正明',
    arranger: '山崎朋子',
  },
  {
    id: 111,
    title: 'あした笑顔になあれ',
    initial: 'あ',
    writer: '渡辺なつみ',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 112,
    title: '明日がくる',
    initial: 'あ',
    writer: '石原一輝',
    composer: '布施美子',
    arranger: '',
  },
  {
    id: 113,
    title: 'あしたのうた',
    initial: 'あ',
    writer: '宮本益光',
    composer: '加藤昌則',
    arranger: '',
  },
  {
    id: 114,
    title: '明日の空へ',
    initial: 'あ',
    writer: 'ミマス',
    composer: 'Sachiko',
    arranger: '富澤裕',
  },
  {
    id: 115,
    title: 'あしたのぼくへ',
    initial: 'あ',
    writer: '里乃塚玲央',
    composer: '森山至貴',
    arranger: '',
  },
  {
    id: 116,
    title: '明日へ',
    initial: 'あ',
    writer: '富岡博志',
    composer: '富岡博志',
    arranger: '',
  },
  {
    id: 117,
    title: '明日へ',
    initial: 'あ',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 118,
    title: '明日へつなぐもの',
    initial: 'あ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 119,
    title: 'あすという日が',
    initial: 'あ',
    writer: '山本瓔子',
    composer: '八木澤教司',
    arranger: '',
  },
  {
    id: 120,
    title: '明日に続く道',
    initial: 'あ',
    writer: '田附奏',
    composer: '田附奏',
    arranger: '',
  },
  {
    id: 121,
    title: '新しい朝',
    initial: 'あ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 122,
    title: 'Adventure',
    initial: 'あ',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 123,
    title: 'あなた',
    initial: 'あ',
    writer: '悠道',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 124,
    title: 'あなたへ 旅立ちに寄せるメッセージ',
    initial: 'あ',
    writer: '筒井雅子',
    composer: '筒井雅子',
    arranger: '',
  },
  {
    id: 125,
    title: 'あなたへのメッセージ',
    initial: 'あ',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 126,
    title: 'あははのうた',
    initial: 'あ',
    writer: 'みなづきみのり',
    composer: '松波千映子',
    arranger: '',
  },
  {
    id: 127,
    title: 'アフリカ音楽の正体 ダイジェスト音源',
    initial: 'あ',
    writer: '',
    composer: '',
    arranger: '',
  },
  {
    id: 128,
    title: '天の川',
    initial: 'あ',
    writer: '藤巻吏絵',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 129,
    title: '天の川のひとしずく',
    initial: 'あ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 130,
    title: '雨上がりの世界へ',
    initial: 'あ',
    writer: '人見敬子',
    composer: '人見敬子',
    arranger: '白川雅樹',
  },
  {
    id: 131,
    title: 'アメイジング・グレイス',
    initial: 'あ',
    writer: '',
    composer: 'James P.Carrell  David S Clayton',
    arranger: '松田昌',
  },
  {
    id: 132,
    title: 'ありがとう',
    initial: 'あ',
    writer: '山本瓔子',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 133,
    title: 'ありがとう',
    initial: 'あ',
    writer: '若松歓',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 134,
    title: 'ありがとう6年生',
    initial: 'あ',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 135,
    title: 'ありがとう〜桜咲く頃また会おう〜',
    initial: 'あ',
    writer: "eye's",
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 136,
    title: 'ありがとう友よ〜末来への輝き〜',
    initial: 'あ',
    writer: '仙台市立西山中学校平成19年度卒業生',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 137,
    title: 'ありがとうの約束',
    initial: 'あ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 138,
    title: '歩きだすときは今',
    initial: 'あ',
    writer: '栗原寛',
    composer: '森山至貴',
    arranger: '',
  },
  {
    id: 139,
    title: 'ＡＲＵＫＩ☆ＤＡＳＯＵ',
    initial: 'あ',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 140,
    title: 'Under the Same Sky',
    initial: 'あ',
    writer: '山本崇雄',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 141,
    title: 'アンパンマンのマーチ',
    initial: 'あ',
    writer: 'やなせたかし',
    composer: '三木たかし',
    arranger: '松田昌',
  },
  {
    id: 201,
    title: '家路',
    initial: 'い',
    writer: '',
    composer: 'ドボルザーク',
    arranger: '松田昌',
  },
  {
    id: 202,
    title: '生きるものたちの賛歌',
    initial: 'い',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 203,
    title: 'いくつもの一瞬',
    initial: 'い',
    writer: '長井理佳',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 204,
    title: '行こうかな どうしよう',
    initial: 'い',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 205,
    title: '行こう どこまでも',
    initial: 'い',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 206,
    title: 'いざたて戦人よ',
    initial: 'い',
    writer: '藤井泰一郎',
    composer: 'マクグラナハン',
    arranger: '',
  },
  {
    id: 207,
    title: 'いただきます',
    initial: 'い',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 208,
    title: '1組カチャーシー',
    initial: 'い',
    writer: '中村彩子',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 209,
    title: '1／1の君に',
    initial: 'い',
    writer: '里乃塚玲央',
    composer: '森山至貴',
    arranger: '',
  },
  {
    id: 210,
    title: '一等星の夢',
    initial: 'い',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 211,
    title: '一歩',
    initial: 'い',
    writer: '中内祥子',
    composer: '理子',
    arranger: 'ruriko',
  },
  {
    id: 212,
    title: 'いつかこの海をこえて',
    initial: 'い',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 213,
    title: 'いつだって青空',
    initial: 'い',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 214,
    title: 'いつまでも',
    initial: 'い',
    writer: '田附奏',
    composer: '田附奏',
    arranger: '',
  },
  {
    id: 215,
    title: 'いつまでも ずっと',
    initial: 'い',
    writer: '松長誠',
    composer: '松長誠',
    arranger: '',
  },
  {
    id: 216,
    title: 'いつまでも伝えたい',
    initial: 'い',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 217,
    title: 'いつも なかよしだよ',
    initial: 'い',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 218,
    title: '生命が羽ばたくとき',
    initial: 'い',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 219,
    title: 'いのちのうた',
    initial: 'い',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 220,
    title: 'いのちの歌',
    initial: 'い',
    writer: 'Ｍｉｙａｂｉ',
    composer: '村松崇継',
    arranger: '富澤裕',
  },
  {
    id: 221,
    title: 'いのちの地図',
    initial: 'い',
    writer: '覚和歌子',
    composer: '信長貴富',
    arranger: '',
  },
  {
    id: 222,
    title: 'イバ・マルタ',
    initial: 'い',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 223,
    title: 'いま',
    initial: 'い',
    writer: '佐藤賢太郎（Ken-P）',
    composer: '佐藤賢太郎（Ken-P）',
    arranger: '',
  },
  {
    id: 224,
    title: '今、卒業の時！',
    initial: 'い',
    writer: '松長誠',
    composer: '松長誠',
    arranger: '',
  },
  {
    id: 225,
    title: 'いまは小さいけれど',
    initial: 'い',
    writer: '石原一輝',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 226,
    title: '今も僕は',
    initial: 'い',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 227,
    title: 'いろいろなかっこう',
    initial: 'い',
    writer: '',
    composer: '',
    arranger: '千田鉄男',
  },
  {
    id: 228,
    title: 'ＩＮ ＴＥＲＲＡ  ＰＡＸ 地に平和を',
    initial: 'い',
    writer: '鶴見正夫',
    composer: '荻久保和明',
    arranger: '',
  },
  {
    id: 301,
    title: 'Ｗｉｔｈ Ｙｏｕ Ｓｍｉｌｅ',
    initial: 'う',
    writer: '水本誠・水本英美',
    composer: '水本誠',
    arranger: '富澤裕',
  },
  {
    id: 302,
    title: 'We are the one',
    initial: 'う',
    writer: '吉岡ひとみ',
    composer: '吉岡ひとみ',
    arranger: '松井孝夫',
  },
  {
    id: 303,
    title: '受けて立つ!!',
    initial: 'う',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 304,
    title: 'うたのクリスマス・プレゼント',
    initial: 'う',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '秋間ゆう子',
  },
  {
    id: 305,
    title: '歌は君〜有志六つの大判焼より',
    initial: 'う',
    writer: '宮原芽映',
    composer: '山本純ノ介',
    arranger: '',
  },
  {
    id: 306,
    title: 'うたはともだち',
    initial: 'う',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 307,
    title: 'うれしい春がきたよ',
    initial: 'う',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 308,
    title: '運命のたまご',
    initial: 'う',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 401,
    title: '笑顔にあえる',
    initial: 'え',
    writer: '里乃塚玲央',
    composer: '富澤裕',
    arranger: '',
  },
  {
    id: 402,
    title: '笑顔のたね',
    initial: 'え',
    writer: 'ますこしょうこ',
    composer: '後藤ミカ',
    arranger: '',
  },
  {
    id: 403,
    title: '笑顔のヒ・ミ・ツ',
    initial: 'え',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 404,
    title: 'エスペランサ〜希望〜',
    initial: 'え',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 501,
    title: 'Oh Happy Wedding!',
    initial: 'お',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 502,
    title: '大空のカーニバル',
    initial: 'お',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 503,
    title: 'Oh My Friend',
    initial: 'お',
    writer: '里乃塚玲央',
    composer: '鈴木行一',
    arranger: '',
  },
  {
    id: 504,
    title: '大村御殿〜じんじん',
    initial: 'お',
    writer: '',
    composer: '沖縄民謡／シバミツ',
    arranger: '',
  },
  {
    id: 505,
    title: 'おくりもの',
    initial: 'お',
    writer: '新沢としひこ',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 506,
    title: 'おしえて',
    initial: 'お',
    writer: '覚和歌子',
    composer: '谷川賢作',
    arranger: '',
  },
  {
    id: 507,
    title: 'オッとあぶないよ！（聖者の行進）',
    initial: 'お',
    writer: '松田昌',
    composer: 'アメリカ民謡',
    arranger: '松田昌',
  },
  {
    id: 508,
    title: 'おどるポンポコリン',
    initial: 'お',
    writer: '',
    composer: '織田哲郎',
    arranger: '松田昌',
  },
  {
    id: 509,
    title: 'おはよう！',
    initial: 'お',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 510,
    title: 'おはよう',
    initial: 'お',
    writer: '工藤直子',
    composer: '瑞慶覧尚子',
    arranger: '',
  },
  {
    id: 511,
    title: 'おはようのエール',
    initial: 'お',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 512,
    title: '終わらない旅へ',
    initial: 'お',
    writer: '大田区立御園中学校卒業生',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 513,
    title: '音楽は友だち',
    initial: 'お',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 514,
    title: 'おんぷのべんきょうしようか',
    initial: 'お',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 1101,
    title: '怪獣のバラード',
    initial: 'か',
    writer: '岡田冨美子',
    composer: '東海林修',
    arranger: '松井孝夫',
  },
  {
    id: 1102,
    title: 'かえるの合唱',
    initial: 'か',
    writer: '',
    composer: 'ドイツ曲',
    arranger: '松田昌',
  },
  {
    id: 1103,
    title: '輝く笑顔',
    initial: 'か',
    writer: '平成18年度浜松市立江南中学校卒業生',
    composer: '平成18年度浜松市立江南中学校卒業生',
    arranger: '渡部哲哉（補作）',
  },
  {
    id: 1104,
    title: '河口',
    initial: 'か',
    writer: '丸山豊',
    composer: '團伊玖磨',
    arranger: '',
  },
  {
    id: 1105,
    title: 'かごめかごめ',
    initial: 'か',
    writer: '',
    composer: 'わらべうた',
    arranger: '松田昌',
  },
  {
    id: 1106,
    title: '風',
    initial: 'か',
    writer: '小高陽子',
    composer: '三善晃',
    arranger: '',
  },
  {
    id: 1107,
    title: '風の跡',
    initial: 'か',
    writer: '星野富弘',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 1108,
    title: '風のことば',
    initial: 'か',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤 裕',
  },
  {
    id: 1109,
    title: '風の子守唄',
    initial: 'か',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 1110,
    title: '風の星 水の星',
    initial: 'か',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '松井孝夫',
  },
  {
    id: 1111,
    title: '風のはじまるところ',
    initial: 'か',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 1112,
    title: '風のマーチ',
    initial: 'か',
    writer: '谷川俊太郎',
    composer: '横山裕美子',
    arranger: '',
  },
  {
    id: 1113,
    title: '風の道しるべ',
    initial: 'か',
    writer: '長井理佳',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 1114,
    title: 'かぜは みんなを ひからせて',
    initial: 'か',
    writer: '渡部千津子',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 1115,
    title: '風よあなたは',
    initial: 'か',
    writer: '山村もも',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 1116,
    title: 'かっこう',
    initial: 'か',
    writer: '',
    composer: 'ドイツ民謡',
    arranger: '松田昌',
  },
  {
    id: 1117,
    title: '悲しみの向こうには',
    initial: 'か',
    writer: '松井孝夫',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 1118,
    title: '歓喜の歌',
    initial: 'か',
    writer: 'シラー／岩佐東一郎（日本語詞）',
    composer: 'ベートーヴェン',
    arranger: '川崎祥悦',
  },
  {
    id: 1119,
    title: 'カントリーレストラン',
    initial: 'か',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 1201,
    title: 'きこえてくる',
    initial: 'き',
    writer: 'まど・みちお',
    composer: '横山潤子',
    arranger: '',
  },
  {
    id: 1202,
    title: '聞こえる',
    initial: 'き',
    writer: '岩間芳樹',
    composer: '新実徳英',
    arranger: '新実徳英',
  },
  {
    id: 1203,
    title: '絆〜キミとボクとのたからもの〜',
    initial: 'き',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 1204,
    title: '奇跡',
    initial: 'き',
    writer: '若松歓',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 1205,
    title: 'きつねのチャチャチャ',
    initial: 'き',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 1206,
    title: '記念日〜希望のバトン〜',
    initial: 'き',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 1207,
    title: '希望という名の花を',
    initial: 'き',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 1208,
    title: '希望の道へ',
    initial: 'き',
    writer: '田附奏',
    composer: '田附奏',
    arranger: '',
  },
  {
    id: 1209,
    title: '希望を胸に大空へ',
    initial: 'き',
    writer: '安城南中学校平成20年度3年生',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 1210,
    title: '君がいたから',
    initial: 'き',
    writer: 'みなづきみのり',
    composer: '横山智昭',
    arranger: '',
  },
  {
    id: 1211,
    title: 'きみがいる教室',
    initial: 'き',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 1212,
    title: '君と歩こう',
    initial: 'き',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 1213,
    title: 'きみと唄う',
    initial: 'き',
    writer: '文月悠光',
    composer: '田中達也',
    arranger: '',
  },
  {
    id: 1214,
    title: '君とみた海',
    initial: 'き',
    writer: '若松歓',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 1215,
    title: 'きみに伝えたい',
    initial: 'き',
    writer: 'LOVE＆英美',
    composer: '水本誠',
    arranger: '富澤裕',
  },
  {
    id: 1216,
    title: 'キミに出会えてよかった',
    initial: 'き',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 1217,
    title: '君のあした',
    initial: 'き',
    writer: '石原一輝',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 1218,
    title: 'きみのかわりはいないから',
    initial: 'き',
    writer: '新沢としひこ',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 1219,
    title: '君の空 君の海',
    initial: 'き',
    writer: '実平雄飛',
    composer: '市川俊明',
    arranger: '',
  },
  {
    id: 1220,
    title: 'きみの友だち',
    initial: 'き',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 1221,
    title: 'キミのもとへ…',
    initial: 'き',
    writer: '吉野莉紗',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 1222,
    title: 'きみはおしえてくれる',
    initial: 'き',
    writer: '新沢としひこ',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 1223,
    title: '君へ',
    initial: 'き',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 1224,
    title: '君を待つ空',
    initial: 'き',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 1225,
    title: 'キャッツアイ',
    initial: 'き',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 1226,
    title: 'キャラバンはつづく',
    initial: 'き',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 1227,
    title: 'Can do〜君が輝くとき〜',
    initial: 'き',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 1228,
    title: '今日からは友だち',
    initial: 'き',
    writer: '杉光麻友子、吉田峰明',
    composer: '吉田峰明',
    arranger: '',
  },
  {
    id: 1229,
    title: '郷愁歌',
    initial: 'き',
    writer: '田附奏',
    composer: '田附奏',
    arranger: '',
  },
  {
    id: 1230,
    title: 'キラキラ キラキラ',
    initial: 'き',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 1231,
    title: 'きらきら星',
    initial: 'き',
    writer: '',
    composer: '',
    arranger: '千田鉄男',
  },
  {
    id: 1232,
    title: 'きらきら星／また会おう、また歌おう',
    initial: 'き',
    writer: '井出隆夫',
    composer:
      'フランス民謡（きらきら星）・上柴はじめ（また会おう、また歌おう）',
    arranger: '上柴はじめ（きらきら星）',
  },
  {
    id: 1233,
    title: 'きらきら星タンギング変奏曲',
    initial: 'き',
    writer: '',
    composer: 'フランス曲',
    arranger: '松田昌',
  },
  {
    id: 1234,
    title: 'きらめく瞬間（とき）',
    initial: 'き',
    writer: 'Ryugo',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 1235,
    title: '木を植える',
    initial: 'き',
    writer: '谷川俊太郎',
    composer: '木下牧子',
    arranger: '',
  },
  {
    id: 1301,
    title: 'くも くも くも',
    initial: 'く',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 1302,
    title: '雲はながれ',
    initial: 'く',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 1303,
    title: 'クラスの星座',
    initial: 'く',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 1304,
    title: 'クラスはオーケストラ',
    initial: 'く',
    writer: '小林一惠',
    composer: '白川雅樹',
    arranger: '',
  },
  {
    id: 1305,
    title: 'Good Day Good Time',
    initial: 'く',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 1401,
    title: '決して泣かない',
    initial: 'け',
    writer: '調布市立第五中学校平成30年度卒業生',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 1402,
    title: '決意',
    initial: 'け',
    writer: '片岡輝',
    composer: '鈴木憲夫',
    arranger: '',
  },
  {
    id: 1403,
    title: 'ゲゲゲの鬼太郎',
    initial: 'け',
    writer: '',
    composer: 'いずみたく',
    arranger: '松田昌',
  },
  {
    id: 1501,
    title: '越えてゆけ',
    initial: 'こ',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 1502,
    title: 'こげよマイケル',
    initial: 'こ',
    writer: '',
    composer: 'スピリチュアル',
    arranger: '松田昌',
  },
  {
    id: 1503,
    title: '心のなかの広い宇宙を',
    initial: 'こ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 1504,
    title: 'ここにしかないものがある',
    initial: 'こ',
    writer: 'つむぐ',
    composer: '相澤直人',
    arranger: '',
  },
  {
    id: 1505,
    title: '心つないで',
    initial: 'こ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 1506,
    title: '心に風が吹いたら',
    initial: 'こ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 1507,
    title: '心の翼 君が広げたら',
    initial: 'こ',
    writer: 'みなづきみのり',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 1508,
    title: '心のなかの広い宇宙を',
    initial: 'こ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 1509,
    title: '心の瞳',
    initial: 'こ',
    writer: '荒木とよひさ',
    composer: '三木たかし',
    arranger: '横山潤子',
  },
  {
    id: 1510,
    title: '心のマストに',
    initial: 'こ',
    writer: '石原一輝',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 1511,
    title: '心ひとつ',
    initial: 'こ',
    writer: '渡瀬昌浩',
    composer: '貫輪久美子',
    arranger: '',
  },
  {
    id: 1512,
    title: 'こころひとつに',
    initial: 'こ',
    writer: '平野次郎',
    composer: '平野次郎',
    arranger: '',
  },
  {
    id: 1513,
    title: '心 ひびきあって',
    initial: 'こ',
    writer: '笹谷幸代',
    composer: '笹谷幸代',
    arranger: '',
  },
  {
    id: 1514,
    title: 'ＣＯＳＭＯＳ',
    initial: 'こ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 1515,
    title: '鼓動',
    initial: 'こ',
    writer: '田中佐知',
    composer: '森山至貴',
    arranger: '',
  },
  {
    id: 1516,
    title: 'この歌を',
    initial: 'こ',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 1517,
    title: 'この地球のどこかで',
    initial: 'こ',
    writer: '三浦恵子',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 1518,
    title: 'この日々を、この時代を',
    initial: 'こ',
    writer: '里乃塚玲央',
    composer: '森山至貴',
    arranger: '',
  },
  {
    id: 1519,
    title: '越えてゆけ',
    initial: 'こ',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 1520,
    title: 'こみちのきもち',
    initial: 'こ',
    writer: '覚 和歌子',
    composer: '信長貴富',
    arranger: '',
  },
  {
    id: 1521,
    title: 'こゆきのおどり',
    initial: 'こ',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 1522,
    title: 'コロブチカ（行商人）',
    initial: 'こ',
    writer: '',
    composer: 'ロシア民謡',
    arranger: '松田昌',
  },
  {
    id: 1523,
    title: 'GO GO! カレーライス',
    initial: 'こ',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 1524,
    title: 'ゴールのない歌',
    initial: 'こ',
    writer: '里乃塚玲央',
    composer: '瑞木薫',
    arranger: '',
  },
  {
    id: 2101,
    title: 'ステップ、スキップ、ジャンプ',
    initial: 'さ',
    writer: '渡瀬昌治',
    composer: '松長誠',
    arranger: '',
  },
  {
    id: 2102,
    title: '桜色',
    initial: 'さ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 2103,
    title: 'さくらの唄',
    initial: 'さ',
    writer: '中内悠介',
    composer: '中内悠介',
    arranger: '',
  },
  {
    id: 2104,
    title: 'さくらの季節',
    initial: 'さ',
    writer: '石原一輝',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 2105,
    title: 'サザエさん',
    initial: 'さ',
    writer: '',
    composer: '筒美京平',
    arranger: '松田昌',
  },
  {
    id: 2106,
    title: 'さようなら',
    initial: 'さ',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 2107,
    title: 'さよならの言葉',
    initial: 'さ',
    writer: '筒井雅子',
    composer: '筒井雅子',
    arranger: '',
  },
  {
    id: 2108,
    title: '「さよなら」の前に',
    initial: 'さ',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 2201,
    title: 'See You Again',
    initial: 'し',
    writer: '若松歓',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 2202,
    title: 'しあわせがあつまるように',
    initial: 'し',
    writer: '山本瓔子',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 2203,
    title: 'Sha ba da ba',
    initial: 'し',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 2204,
    title: 'シューベルトの子守歌',
    initial: 'し',
    writer: '',
    composer: 'シューベルト',
    arranger: '松田昌',
  },
  {
    id: 2205,
    title: '信じる',
    initial: 'し',
    writer: '谷川俊太郎',
    composer: '松下耕',
    arranger: '',
  },
  {
    id: 2206,
    title: 'ジェリコの戦い',
    initial: 'し',
    writer: 'スピリチュアル',
    composer: 'スピリチュアル',
    arranger: '河西保郎',
  },
  {
    id: 2207,
    title: 'Jump!',
    initial: 'し',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 2208,
    title: '十歳の記念日',
    initial: 'し',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 2209,
    title: '10歳を向かえる日に',
    initial: 'し',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 2301,
    title: 'スキキライ・シャッフル',
    initial: 'す',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 2302,
    title: 'スペインのカスタネット',
    initial: 'す',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 2303,
    title: 'スマイル・スマイル',
    initial: 'す',
    writer: '高木冨士子',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 2304,
    title: 'ずっとずっと',
    initial: 'す',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 2401,
    title: '青春メモリーズ',
    initial: 'せ',
    writer: '原田薫',
    composer: '岡崎絵美（向陽中学校三年生補作）',
    arranger: '',
  },
  {
    id: 2402,
    title: '生命が羽ばたくとき',
    initial: 'せ',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 2403,
    title: 'せかいじゅうかいじゅう',
    initial: 'せ',
    writer: 'ごとうやすゆき',
    composer: '横山智昭',
    arranger: '',
  },
  {
    id: 2404,
    title: '世界でひとつのハーモニー',
    initial: 'せ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 2405,
    title: '世界の子どものマーチ',
    initial: 'せ',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 2406,
    title: 'ぜんぶ〜卒業式バージョン〜',
    initial: 'せ',
    writer: 'さくらももこ',
    composer: '相澤直人',
    arranger: '',
  },
  {
    id: 2407,
    title: 'ぜんぶ忘れない',
    initial: 'せ',
    writer: '桑原永江',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 2501,
    title: '卒業〜ありがとう いつまでも〜',
    initial: 'そ',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 2502,
    title: '卒業アルバム',
    initial: 'そ',
    writer: '織田ゆり子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 2503,
    title: 'その手をください',
    initial: 'そ',
    writer: '大田倭子',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 2504,
    title: 'そよ風のように',
    initial: 'そ',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 2505,
    title: '空',
    initial: 'そ',
    writer: '新川和江',
    composer: '三宅悠太',
    arranger: '',
  },
  {
    id: 2506,
    title: 'ソラシドマーチ',
    initial: 'そ',
    writer: '織田ゆり子',
    composer: '上柴はじめ',
    arranger: '上柴はじめ',
  },
  {
    id: 2507,
    title: '空にジャンプ！',
    initial: 'そ',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 2508,
    title: '空の美術館',
    initial: 'そ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 2509,
    title: '空の文字',
    initial: 'そ',
    writer: '門倉詇',
    composer: '佐々木信綱',
    arranger: '',
  },
  {
    id: 2510,
    title: '空のように青い心で',
    initial: 'そ',
    writer: '新沢としひこ',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 2511,
    title: '空にジャンプ！',
    initial: 'そ',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 2512,
    title: 'それぞれの夢へと',
    initial: 'そ',
    writer: '愛知県安城南中学校平成24年度2年生',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 3101,
    title: 'たいせつなあなたへ',
    initial: 'た',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 3102,
    title: '大切なともだち',
    initial: 'た',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 3103,
    title: '大切なもの',
    initial: 'た',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 3104,
    title: 'たいせつに…',
    initial: 'た',
    writer: '松井孝夫',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 3105,
    title: '太陽と大地の子供たち',
    initial: 'た',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3106,
    title: '太陽の国へ',
    initial: 'た',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 3107,
    title: '太陽のパレード',
    initial: 'た',
    writer: '弥勒',
    composer: '瑞木薫',
    arranger: '',
  },
  {
    id: 3108,
    title: 'たからもの',
    initial: 'た',
    writer: '工藤直子',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 3109,
    title: 'たしかな一歩',
    initial: 'た',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 3110,
    title: 'たのしくタンギング',
    initial: 'た',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 3111,
    title: '旅立ちの時〜Ａｓｉａｎ Ｄｒｅａｍ Ｓｏｎｇ〜',
    initial: 'た',
    writer: 'ドリアン助川',
    composer: '久石譲',
    arranger: '富澤裕',
  },
  {
    id: 3112,
    title: '旅立ちの日に',
    initial: 'た',
    writer: '小嶋登',
    composer: '坂本浩美',
    arranger: '松井孝夫',
  },
  {
    id: 3113,
    title: '旅立つ君へ',
    initial: 'た',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 3114,
    title: '大好きって気持ち',
    initial: 'た',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3115,
    title: '大地讃頌',
    initial: 'た',
    writer: '大木惇夫',
    composer: '佐藤眞',
    arranger: '',
  },
  {
    id: 3116,
    title: '大地に生きる',
    initial: 'た',
    writer: '市川文保／笹谷幸代（補作詞）',
    composer: '笹谷幸代',
    arranger: '',
  },
  {
    id: 3117,
    title: 'Dabiduba Dubiduba',
    initial: 'た',
    writer: '松本比呂',
    composer: '松本比呂',
    arranger: '',
  },
  {
    id: 3118,
    title: 'だれのものでもない今を',
    initial: 'た',
    writer: '森山至貴',
    composer: '森山至貴',
    arranger: '',
  },
  {
    id: 3201,
    title: '小さな時間',
    initial: 'ち',
    writer: '山本瓔子',
    composer: '八木澤教司',
    arranger: '',
  },
  {
    id: 3202,
    title: '小さな勇気',
    initial: 'ち',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 3203,
    title: 'Change!',
    initial: 'ち',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 3204,
    title: 'アロハ！地球',
    initial: 'ち',
    writer: '中村彩子',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 3205,
    title: '地球星歌〜笑顔のために〜',
    initial: 'ち',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 3206,
    title: '地球に乾杯！',
    initial: 'ち',
    writer: '山村もも',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 3207,
    title: '地球の歌',
    initial: 'ち',
    writer: '門倉詇',
    composer: '吉岡弘行',
    arranger: '',
  },
  {
    id: 3208,
    title: '地球のかぞく',
    initial: 'ち',
    writer: '石原一輝',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 3209,
    title: '地球の鼓動',
    initial: 'ち',
    writer: '弥勒',
    composer: '瑞木薫',
    arranger: '',
  },
  {
    id: 3210,
    title: '地球のなかまたち',
    initial: 'ち',
    writer: '工藤直子',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 3211,
    title: '地球は青い宇宙船',
    initial: 'ち',
    writer: 'みなづきみのり',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 3212,
    title: '地球はまわる',
    initial: 'ち',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 3213,
    title: '地球は廻る',
    initial: 'ち',
    writer: '渡辺なつみ',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3214,
    title: '小さな冒険者たち',
    initial: 'ち',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3215,
    title: '茶色の小びん',
    initial: 'ち',
    writer: '',
    composer: 'J.ウィンナー',
    arranger: '松田昌',
  },
  {
    id: 3216,
    title: 'チューリップ',
    initial: 'ち',
    writer: '',
    composer: '井上武士',
    arranger: '松田昌',
  },
  {
    id: 3217,
    title: '地球は青い宇宙船',
    initial: 'ち',
    writer: 'みなづきみのり',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 3301,
    title: '次の空へ',
    initial: 'つ',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 3302,
    title: 'つないで歌おう',
    initial: 'つ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 3303,
    title: 'つながる空',
    initial: 'つ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 3304,
    title: 'つばさにかえて',
    initial: 'つ',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 3305,
    title: '翼を広げて',
    initial: 'つ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 3306,
    title: 'つぼみが開くように',
    initial: 'つ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 3307,
    title: 'つむぐ思い',
    initial: 'つ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 3308,
    title: 'つよくなれ',
    initial: 'つ',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 3401,
    title: 'Take off!-夢に向かって-',
    initial: 'て',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3402,
    title: '手紙〜拝啓 十五の君へ〜',
    initial: 'て',
    writer: 'アンジェラ・アキ',
    composer: 'アンジェラ・アキ',
    arranger: '鷹羽弘晃',
  },
  {
    id: 3403,
    title: '出会い',
    initial: 'て',
    writer: '山本恵三子',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 3404,
    title: '出会いたくて',
    initial: 'て',
    writer: '松任谷正夫',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 3405,
    title: 'Departure 旅立つ君へ',
    initial: 'て',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 3501,
    title: '透明な光あふれる日〜スコットランドの子守唄の調べにのせて',
    initial: 'と',
    writer: '月波ユノ',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 3502,
    title: '遠い空の下で',
    initial: 'と',
    writer: '宮本益光',
    composer: '加藤昌則',
    arranger: '',
  },
  {
    id: 3503,
    title: '遠い日の歌（パッヘルベルのカノンによる）',
    initial: 'と',
    writer: '若沢千早',
    composer: '橋本祥路',
    arranger: '',
  },
  {
    id: 3504,
    title: '遠く',
    initial: 'と',
    writer: '覚和歌子',
    composer: '信長貴富',
    arranger: '',
  },
  {
    id: 3505,
    title: '時代',
    initial: 'と',
    writer: '富永良吉',
    composer: '渡邉泰祐',
    arranger: '',
  },
  {
    id: 3506,
    title: '時のおくりもの',
    initial: 'と',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 3507,
    title: '時の彼方へ',
    initial: 'と',
    writer: 'フルリーナ',
    composer: '富澤裕',
    arranger: '',
  },
  {
    id: 3508,
    title: '時を越えて',
    initial: 'と',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 3509,
    title: 'となりのねこちゃん',
    initial: 'と',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 3510,
    title: '友〜旅立ちの時〜',
    initial: 'と',
    writer: '北川悠仁',
    composer: '北川悠仁',
    arranger: '相澤直人',
  },
  {
    id: 3511,
    title: '友だち〜心の名まえ',
    initial: 'と',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3512,
    title: 'ともだち鏡',
    initial: 'と',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 3513,
    title: 'ともだちになろうよ',
    initial: 'と',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 3514,
    title: '友よ  その日まで',
    initial: 'と',
    writer: '東龍男',
    composer: '横山潤子',
    arranger: '',
  },
  {
    id: 3515,
    title: 'Dream & Dream〜夢をつなごう〜',
    initial: 'と',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 3516,
    title: 'どんなときも',
    initial: 'と',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 4101,
    title: 'なーんだ地球はちいさいね',
    initial: 'な',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 4102,
    title: 'NAKAMA',
    initial: 'な',
    writer: '松本比呂',
    composer: '松本比呂',
    arranger: '',
  },
  {
    id: 4103,
    title: '夏の音がきこえる',
    initial: 'な',
    writer: '藤巻吏絵',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 4104,
    title: '夏の日の贈りもの',
    initial: 'な',
    writer: '高木あきこ',
    composer: '加賀清孝',
    arranger: '',
  },
  {
    id: 4105,
    title: '名づけられた葉',
    initial: 'な',
    writer: '新川和江',
    composer: '飯沼信義',
    arranger: '',
  },
  {
    id: 4106,
    title: 'なんども なんどでも',
    initial: 'な',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 4201,
    title: '虹色のハーモニー',
    initial: 'に',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 4202,
    title: '虹が生まれる',
    initial: 'に',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 4203,
    title: '虹―七色の音―',
    initial: 'に',
    writer: '関谷祐人・浦川光一',
    composer: '樹原孝之介',
    arranger: '樹原孝之介',
  },
  {
    id: 4204,
    title: '虹に向かって',
    initial: 'に',
    writer: '小栗克裕',
    composer: '小栗克裕',
    arranger: '',
  },
  {
    id: 4205,
    title: '虹の麓の宝物',
    initial: 'に',
    writer: '筒井雅子',
    composer: '筒井雅子',
    arranger: '',
  },
  {
    id: 4206,
    title: '虹を渡って',
    initial: 'に',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 4207,
    title: '人間っていいね！',
    initial: 'に',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 4501,
    title: '野空海（のぞみ）',
    initial: 'の',
    writer: '吉岡ひとみ',
    composer: '吉岡ひとみ',
    arranger: '松井孝夫',
  },
  {
    id: 4502,
    title: 'のんびり ひるね',
    initial: 'の',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 5101,
    title: 'How wonderful living together!（生きてるってすばらしい）',
    initial: 'は',
    writer: '山村もも',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 5102,
    title: '方舟地球号は僕たちをのせて',
    initial: 'は',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 5103,
    title: '走る川',
    initial: 'は',
    writer: '金沢智恵子',
    composer: '黒沢吉徳',
    arranger: '',
  },
  {
    id: 5104,
    title: 'はじまり',
    initial: 'は',
    writer: '工藤直子',
    composer: '木下牧子',
    arranger: '',
  },
  {
    id: 5105,
    title: 'はじまりの歌',
    initial: 'は',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 5106,
    title: 'はじまりの気持ち',
    initial: 'は',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 5107,
    title: '始まりのさよなら',
    initial: 'は',
    writer: '貫輪久美子',
    composer: '貫輪久美子',
    arranger: '',
  },
  {
    id: 5108,
    title: 'はじまりの予感',
    initial: 'は',
    writer: '栗原寛',
    composer: '大藤史',
    arranger: '',
  },
  {
    id: 5109,
    title: 'ハッピー・クリスマス・トゥー・ユー',
    initial: 'は',
    writer: '中村彩子',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 5110,
    title: 'ハッピーマジック',
    initial: 'は',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 5111,
    title: 'HAPPY MUSIC',
    initial: 'は',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 5112,
    title: 'ハッピー・メロディー',
    initial: 'は',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 5113,
    title: '花笑',
    initial: 'は',
    writer: '弥勒',
    composer: '瑞木薫',
    arranger: '',
  },
  {
    id: 5114,
    title: '花束',
    initial: 'は',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 5115,
    title: '花は咲く',
    initial: 'は',
    writer: '岩井俊二',
    composer: '菅野よう子',
    arranger: '氏家晋也',
  },
  {
    id: 5116,
    title: '花丸ロックンロール',
    initial: 'は',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 5117,
    title: '花をさがす少女',
    initial: 'は',
    writer: '鶴見正夫',
    composer: '荻久保和明',
    arranger: '',
  },
  {
    id: 5118,
    title: 'はばたこう明日へ',
    initial: 'は',
    writer: '松井孝夫',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 5119,
    title: 'はらっぱのうた',
    initial: 'は',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 5120,
    title: 'はる',
    initial: 'は',
    writer: '谷川俊太郎',
    composer: '相澤直人',
    arranger: '',
  },
  {
    id: 5121,
    title: '春に',
    initial: 'は',
    writer: '谷川俊太郎',
    composer: '木下牧子',
    arranger: '',
  },
  {
    id: 5122,
    title: 'Hello! My Best Friend',
    initial: 'は',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 5123,
    title: 'パーム・パーム',
    initial: 'は',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 5124,
    title: 'パルマ！',
    initial: 'は',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 5125,
    title: 'パレードがやってくる！',
    initial: 'は',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 5126,
    title: 'Power of Dreem〜夢のちから〜',
    initial: 'は',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 5201,
    title: '光の射す方へ',
    initial: 'ひ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 5202,
    title: '光のなかで',
    initial: 'ひ',
    writer: '若松歓',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 5203,
    title: 'ひとつになりたい',
    initial: 'ひ',
    writer: '青島江里',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 5204,
    title: '一つの明かりで',
    initial: 'ひ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 5205,
    title: 'ひとつの朝',
    initial: 'ひ',
    writer: '片岡輝',
    composer: '平吉毅州',
    arranger: '',
  },
  {
    id: 5206,
    title: 'ひとつの勇気',
    initial: 'ひ',
    writer: '渡瀬昌治',
    composer: '松長 誠',
    arranger: '',
  },
  {
    id: 5207,
    title: 'ひとりになった ひ',
    initial: 'ひ',
    writer: '織江りょう',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 5208,
    title: '火の山の子守歌',
    initial: 'ひ',
    writer: '谷川雁',
    composer: '新実徳英',
    arranger: '',
  },
  {
    id: 5209,
    title: '響きあう命',
    initial: 'ひ',
    writer: '西部敏彦',
    composer: '瑞木薫',
    arranger: '',
  },
  {
    id: 5210,
    title: 'ひらり、',
    initial: 'ひ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 5211,
    title: '広い世界が待っている',
    initial: 'ひ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 5212,
    title: 'Ｂｅｌｉｅｖｅ',
    initial: 'ひ',
    writer: '杉本竜一',
    composer: '杉本竜一',
    arranger: '富澤裕',
  },
  {
    id: 5213,
    title: 'ぴったりちょうど',
    initial: 'ひ',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 5301,
    title: 'ふたつの海',
    initial: 'ふ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 5302,
    title: 'ふるさと',
    initial: 'ふ',
    writer: '',
    composer: '岡野貞一',
    arranger: '松田昌',
  },
  {
    id: 5303,
    title: 'ふるさとへ帰ろう',
    initial: 'ふ',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 5304,
    title: 'Friends of Stars 宇宙への手紙',
    initial: 'ふ',
    writer: '宮下路乃',
    composer: '宮下路乃',
    arranger: '',
  },
  {
    id: 5305,
    title: 'friends―ともに未来へ―',
    initial: 'ふ',
    writer: 'ごとうやすゆき',
    composer: '横山智昭',
    arranger: '',
  },
  {
    id: 5306,
    title: 'ブリッジ',
    initial: 'ふ',
    writer: '桜田直子',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 5307,
    title: 'ぶんぶんぶん',
    initial: 'ふ',
    writer: '',
    composer: 'ボヘミヤ民謡',
    arranger: '松田昌',
  },
  {
    id: 5401,
    title: 'ＨＥＩＷＡの鐘',
    initial: 'へ',
    writer: '仲里幸広',
    composer: '仲里幸広',
    arranger: '白石哲也',
  },
  {
    id: 5402,
    title: 'ベレント・ボッチェ（オランダの民謡より）',
    initial: 'へ',
    writer: '',
    composer: 'オランダ民謡',
    arranger: '中村彩子',
  },
  {
    id: 5501,
    title: '誇り',
    initial: 'ほ',
    writer: '覚和歌子',
    composer: '高嶋みどり',
    arranger: '',
  },
  {
    id: 5502,
    title: '星に誓いを',
    initial: 'ほ',
    writer: '片岡輝',
    composer: '瑞木薫',
    arranger: '',
  },
  {
    id: 5503,
    title: '星の大地に',
    initial: 'ほ',
    writer: '石原一輝',
    composer: '桜田直子',
    arranger: '',
  },
  {
    id: 5504,
    title: '星の光の羅針盤',
    initial: 'ほ',
    writer: '早坂類',
    composer: '田中達也',
    arranger: '',
  },
  {
    id: 5505,
    title: '星降る里〜Feer the Starry Sky〜',
    initial: 'ほ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 5506,
    title: '星降る夜',
    initial: 'ほ',
    writer: 'フルリーナ',
    composer: '富澤裕',
    arranger: '',
  },
  {
    id: 5507,
    title: 'Voyager',
    initial: 'ほ',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 5508,
    title: 'Voices',
    initial: 'ほ',
    writer: '松本比呂',
    composer: '松本比呂',
    arranger: '',
  },
  {
    id: 5509,
    title: '僕たちよ、風になれ',
    initial: 'ほ',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 5510,
    title: 'ぼくにはわかる',
    initial: 'ほ',
    writer: '高崎乃理子',
    composer: '横山潤子',
    arranger: '',
  },
  {
    id: 5511,
    title: 'ぼくの太陽',
    initial: 'ほ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 5512,
    title: '僕の宝物',
    initial: 'ほ',
    writer: '平成18年度浜松市立江南中学校卒業生',
    composer: '平成18年度浜松市立江南中学校卒業生',
    arranger: '渡部哲哉（補作）',
  },
  {
    id: 5513,
    title: 'ぼくはカブトムシ',
    initial: 'ほ',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 5514,
    title: 'ぼくらの軌跡',
    initial: 'ほ',
    writer: '石原一輝',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 5515,
    title: 'ボクらの時代',
    initial: 'ほ',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 5516,
    title: 'ぼくらの秘密基地',
    initial: 'ほ',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 5517,
    title: 'ぼくらのふるさと',
    initial: 'ほ',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 5518,
    title: 'ぼくらの未来へ',
    initial: 'ほ',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 5519,
    title: 'ぼくらは音楽隊',
    initial: 'ほ',
    writer: '細川眞理子',
    composer: '細川眞理子',
    arranger: '',
  },
  {
    id: 5520,
    title: 'ポラリスの大地−「ソーラン節」の主題による−',
    initial: 'ほ',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 6101,
    title: 'マイ バラード',
    initial: 'ま',
    writer: '松井孝夫',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 6102,
    title: '前へ！',
    initial: 'ま',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 6103,
    title: 'まくをあけよう',
    initial: 'ま',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 6104,
    title: 'またあした',
    initial: 'ま',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 6105,
    title: 'まっさらなパレット',
    initial: 'ま',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 6106,
    title: 'まってるよ',
    initial: 'ま',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 6107,
    title: '窓を開けよう',
    initial: 'ま',
    writer: '大谷惠美',
    composer: '上柴はじめ',
    arranger: '',
  },
  {
    id: 6108,
    title: '魔法のあいことば',
    initial: 'ま',
    writer: '古宮真美子',
    composer: '古宮真美子',
    arranger: '',
  },
  {
    id: 6109,
    title: 'まるい地球をひとまわり',
    initial: 'ま',
    writer: 'ミマス',
    composer: 'ミマス',
    arranger: '富澤裕',
  },
  {
    id: 6201,
    title: '見えない翼',
    initial: 'み',
    writer: '佐々木香',
    composer: '長倉鈴恵',
    arranger: '',
  },
  {
    id: 6202,
    title: '道標（みち）',
    initial: 'み',
    writer: '清水宏美',
    composer: '清水宏美',
    arranger: '田附奏',
  },
  {
    id: 6203,
    title: '道',
    initial: 'み',
    writer: 'Ｓｈｏｇｏ　ｋａｓｈｉｄａ',
    composer: 'ｍｉｗａ　ｆｕｒｕｓｅ',
    arranger: '若松歓',
  },
  {
    id: 6204,
    title: '未知へ',
    initial: 'み',
    writer: '木村信子',
    composer: '信長貴富',
    arranger: '',
  },
  {
    id: 6205,
    title: '見ててね',
    initial: 'み',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 6206,
    title: 'MIDORI〜繋がる輪〜',
    initial: 'み',
    writer: '菊本るり子',
    composer: '菊本るり子',
    arranger: '',
  },
  {
    id: 6207,
    title: 'MUSIC',
    initial: 'み',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 6208,
    title: '未来',
    initial: 'み',
    writer: '谷川俊太郎',
    composer: '高嶋みどり',
    arranger: '',
  },
  {
    id: 6209,
    title: '未来が生まれてる',
    initial: 'み',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 6210,
    title: '未来につなげ〜記念日に歌う歌〜',
    initial: 'み',
    writer: '松長誠',
    composer: '松長誠',
    arranger: '',
  },
  {
    id: 6211,
    title: '未来のつくり方',
    initial: 'み',
    writer: '里乃塚玲央',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 6212,
    title: '未来はいま',
    initial: 'み',
    writer: '横山智昭',
    composer: '横山智昭',
    arranger: '',
  },
  {
    id: 6213,
    title: '未来へ',
    initial: 'み',
    writer: '谷川俊太郎',
    composer: '信長貴富',
    arranger: '',
  },
  {
    id: 6214,
    title: '未来へ',
    initial: 'み',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 6215,
    title: '未来へ一歩',
    initial: 'み',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 6216,
    title: '未来へと',
    initial: 'み',
    writer: '藤巻吏絵',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 6217,
    title: '未来へ届け',
    initial: 'み',
    writer: '山崎朋子',
    composer: '山崎朋子',
    arranger: '',
  },
  {
    id: 6218,
    title: '未来行きEXPRESS',
    initial: 'み',
    writer: '筒井雅子',
    composer: '筒井雅子',
    arranger: '',
  },
  {
    id: 6219,
    title: '未来よ',
    initial: 'み',
    writer: '覚和歌子',
    composer: '高嶋みどり',
    arranger: '',
  },
  {
    id: 6220,
    title: '未来を信じて',
    initial: 'み',
    writer: '渡瀬昌治',
    composer: '大田桜子',
    arranger: '',
  },
  {
    id: 6221,
    title: 'みんな大好き',
    initial: 'み',
    writer: 'ruriko',
    composer: 'ruriko',
    arranger: '',
  },
  {
    id: 6222,
    title: 'みんなの世界',
    initial: 'み',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 6223,
    title: '村の幸い祭り',
    initial: 'み',
    writer: '河原木孝浩',
    composer: '河原木孝浩',
    arranger: '',
  },
  {
    id: 6401,
    title: 'メヌエット',
    initial: 'め',
    writer: '',
    composer: 'ペツォルト',
    arranger: '松田昌',
  },
  {
    id: 6402,
    title: 'ME BU KI めぶきのビート',
    initial: 'め',
    writer: '',
    composer: '中村彩子',
    arranger: '',
  },
  {
    id: 6501,
    title: '木星 Jupiter',
    initial: 'も',
    writer: '',
    composer: 'ホルスト',
    arranger: '松田昌',
  },
  {
    id: 6502,
    title: 'モグモグ モグラ',
    initial: 'も',
    writer: '人見敬子',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 6503,
    title: 'モルダウ',
    initial: 'も',
    writer: '岩河三郎',
    composer: 'スメタナ',
    arranger: '岩河三郎',
  },
  {
    id: 7101,
    title: '約束の言葉はどうして',
    initial: 'や',
    writer: '人見敬子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 7102,
    title: '約束をしたね',
    initial: 'や',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 7103,
    title: 'やさしさのかけら',
    initial: 'や',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 7104,
    title: '山の音楽家',
    initial: 'や',
    writer: '',
    composer: 'ドイツ民謡',
    arranger: '松田昌',
  },
  {
    id: 7301,
    title: '勇気のうた',
    initial: 'ゆ',
    writer: '若松歓',
    composer: '若松歓',
    arranger: '',
  },
  {
    id: 7302,
    title: '勇気のマーチ',
    initial: 'ゆ',
    writer: '人見敬子',
    composer: '氏家晋也',
    arranger: '',
  },
  {
    id: 7303,
    title: '勇気を力にかえて',
    initial: 'ゆ',
    writer: '渡瀬昌治',
    composer: '松井孝夫',
    arranger: '',
  },
  {
    id: 7304,
    title: '夕ぐれの街',
    initial: 'ゆ',
    writer: '',
    composer: '千田鉄男',
    arranger: '',
  },
  {
    id: 7305,
    title: 'ゆびのロンド（メリーさんのひつじ）',
    initial: 'ゆ',
    writer: '松田昌',
    composer: 'マザーグースより',
    arranger: '松田昌',
  },
  {
    id: 7501,
    title: '夢',
    initial: 'よ',
    writer: '工藤直子',
    composer: '上柴はじめ',
    arranger: '',
  },
  {
    id: 7502,
    title: 'ゆりいす',
    initial: 'よ',
    writer: '工藤直子',
    composer: '木下牧子',
    arranger: '',
  },
  {
    id: 7503,
    title: '夜明け',
    initial: 'よ',
    writer: '北海道旭川商業高校吹奏楽部平成10年度卒部生一同',
    composer: '八幡映美',
    arranger: '富澤裕',
  },
  {
    id: 7504,
    title: 'よいしょが いっぱい',
    initial: 'よ',
    writer: '工藤直子',
    composer: '瑞慶覧尚子',
    arranger: '',
  },
  {
    id: 7505,
    title: '喜びの歌',
    initial: 'よ',
    writer: '',
    composer: 'ベートーヴェン',
    arranger: '松田昌',
  },
  {
    id: 8101,
    title: 'ラララ ミュージック',
    initial: 'ら',
    writer: '美鈴こゆき',
    composer: '美鈴こゆき',
    arranger: '',
  },
  {
    id: 8202,
    title: '立志式',
    initial: 'り',
    writer: '吉岡ひとみ',
    composer: '吉岡ひとみ',
    arranger: '松井孝夫',
  },
  {
    id: 8203,
    title: 'リフレイン',
    initial: 'り',
    writer: '覚 和歌子',
    composer: '信長貴富',
    arranger: '',
  },
  {
    id: 8301,
    title: '流浪の民',
    initial: 'る',
    writer: '石倉小三郎（訳詞）',
    composer: 'シューマン',
    arranger: '市川都志春',
  },
  {
    id: 8401,
    title: 'レッツゴー！あしたへ',
    initial: 'れ',
    writer: '栂野知子',
    composer: '栂野知子',
    arranger: '',
  },
  {
    id: 8402,
    title: 'Let’s Go! TAMAGO!!',
    initial: 'れ',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 8403,
    title: 'Ｌｅｔ’ｓ Ｓｅａｒｃｈ Ｆｏｒ Ｔｏｍｏｒｒｏｗ',
    initial: 'れ',
    writer: '堀徹',
    composer: '大澤徹訓',
    arranger: '',
  },
  {
    id: 8404,
    title: "Let's Fly!",
    initial: 'れ',
    writer: '筒井雅子',
    composer: '筒井雅子',
    arranger: '',
  },
  {
    id: 8501,
    title: '６年間のたからもの',
    initial: 'ろ',
    writer: 'ミマス、KEN♪',
    composer: 'ミマス、KEN♪',
    arranger: '西澤健治',
  },
  {
    id: 8502,
    title: 'ロマンス',
    initial: 'ろ',
    writer: '',
    composer: 'モーツァルト',
    arranger: '松田昌',
  },
  {
    id: 9101,
    title: 'わかちあうものたちへ',
    initial: 'わ',
    writer: '長生淳',
    composer: '長生淳',
    arranger: '',
  },
  {
    id: 9102,
    title: '忘れない',
    initial: 'わ',
    writer: '弓削田健介',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 9103,
    title: 'わたあめ',
    initial: 'わ',
    writer: '河室賢明',
    composer: '弓削田健介',
    arranger: '',
  },
  {
    id: 9104,
    title: 'わたしと小鳥とすずと',
    initial: 'わ',
    writer: '金子みすゞ',
    composer: '横山裕美子',
    arranger: '',
  },
  {
    id: 9105,
    title: 'わたしニンジン',
    initial: 'わ',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
  {
    id: 9106,
    title: 'One Family',
    initial: 'わ',
    writer: '大森祥子',
    composer: '西澤健治',
    arranger: '',
  },
]

export default songs
